# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sensor_name', models.CharField(max_length=200)),
            ],
        ),
    ]
