# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170320_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
